// GENERATED by scripts/optimize-images.mjs — do not edit by hand.
export const images = {
  "about": {
    "width": 2400,
    "height": 1350
  },
  "detail": {
    "width": 2400,
    "height": 1600
  }
} as const

export type ImageName = keyof typeof images
