/**
 * src-images/*.jpg  →  public/img/{name}-{width}.{avif,webp,jpg}
 *                   →  src/assets/images.ts  (typed manifest)
 *
 * Run with `npm run images`. Output is committed, so the build itself does no
 * image work and the owner can see exactly what will be uploaded.
 */
import sharp from 'sharp'
import { readdir, mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

const SRC = 'src-images'
const OUT = 'public/img'
const MANIFEST = 'src/assets/images.ts'
const WIDTHS = [480, 768, 1120, 1600]

await mkdir(OUT, { recursive: true })

const files = (await readdir(SRC)).filter((f) => /\.(jpe?g|png)$/i.test(f))
if (!files.length) {
  console.error(`No source images in ${SRC}/`)
  process.exit(1)
}

const manifest = {}

for (const file of files) {
  const name = path.parse(file).name
  const input = path.join(SRC, file)
  const meta = await sharp(input).metadata()
  manifest[name] = { width: meta.width, height: meta.height }

  for (const w of WIDTHS) {
    if (w > meta.width) continue
    const base = sharp(input).resize({ width: w, withoutEnlargement: true })
    await Promise.all([
      base.clone().avif({ quality: 52, effort: 6 }).toFile(`${OUT}/${name}-${w}.avif`),
      base.clone().webp({ quality: 74 }).toFile(`${OUT}/${name}-${w}.webp`),
      base
        .clone()
        .jpeg({ quality: 78, mozjpeg: true, progressive: true })
        .toFile(`${OUT}/${name}-${w}.jpg`),
    ])
  }
  console.log(`✓ ${name}  ${meta.width}×${meta.height}`)
}

const body = `// GENERATED by scripts/optimize-images.mjs — do not edit by hand.
export const images = ${JSON.stringify(manifest, null, 2)} as const

export type ImageName = keyof typeof images
`
await writeFile(MANIFEST, body)
console.log(`✓ ${MANIFEST}`)
